/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ventanas;

import conexion.Conexionbd;

/**
 *
 * @author Steven Dj
 */
public class Menu extends javax.swing.JFrame {
    Conexionbd con = new Conexionbd();
    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
       this.setLocationRelativeTo(null); 
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        BtCLiente = new javax.swing.JButton();
        BtVentas = new javax.swing.JButton();
        BtProductos = new javax.swing.JButton();
        BtProveedor = new javax.swing.JButton();
        Btexit = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));

        BtCLiente.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BtCLiente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/usuario.png"))); // NOI18N
        BtCLiente.setText("Agregar Clientes");
        BtCLiente.setBorder(null);
        BtCLiente.setContentAreaFilled(false);
        BtCLiente.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtCLiente.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/usuariomini.png"))); // NOI18N
        BtCLiente.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BtCLiente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtCLienteMouseClicked(evt);
            }
        });
        BtCLiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtCLienteActionPerformed(evt);
            }
        });

        BtVentas.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BtVentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/vemya.png"))); // NOI18N
        BtVentas.setText("Nueva Venta");
        BtVentas.setBorder(null);
        BtVentas.setContentAreaFilled(false);
        BtVentas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtVentas.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ventamini.png"))); // NOI18N
        BtVentas.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BtVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtVentasActionPerformed(evt);
            }
        });

        BtProductos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BtProductos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/productoo.png"))); // NOI18N
        BtProductos.setText("Agragar Producto");
        BtProductos.setBorder(null);
        BtProductos.setContentAreaFilled(false);
        BtProductos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtProductos.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/productomini.png"))); // NOI18N
        BtProductos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BtProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtProductosActionPerformed(evt);
            }
        });

        BtProveedor.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BtProveedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/proveedor.png"))); // NOI18N
        BtProveedor.setText("Agregar Proveedor");
        BtProveedor.setBorder(null);
        BtProveedor.setContentAreaFilled(false);
        BtProveedor.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtProveedor.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Proveedormini.png"))); // NOI18N
        BtProveedor.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BtProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtProveedorActionPerformed(evt);
            }
        });

        Btexit.setText("Cerrar Sesion");
        Btexit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtexitMouseClicked(evt);
            }
        });

        jButton1.setText("Ver todos clientes");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Consultar ventas");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Ver bodega");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Ver proveedores");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Datos de la empresa");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(BtCLiente)
                        .addGap(18, 18, 18)
                        .addComponent(BtVentas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BtProductos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BtProveedor))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(278, 278, 278)
                        .addComponent(Btexit, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BtProveedor)
                    .addComponent(BtProductos)
                    .addComponent(BtVentas)
                    .addComponent(BtCLiente))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Btexit)
                    .addComponent(jButton5))
                .addGap(50, 50, 50))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtProveedorActionPerformed
 Proveedor proveedor= new Proveedor ();
 proveedor.setVisible(true);
 this.dispose();
    }//GEN-LAST:event_BtProveedorActionPerformed

    private void BtexitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtexitMouseClicked
     Login exit=new Login();
     exit.setVisible(true);
     this.dispose();
    }//GEN-LAST:event_BtexitMouseClicked

    private void BtCLienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtCLienteMouseClicked
        Clientes cliente= new Clientes ();
        cliente.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BtCLienteMouseClicked

    private void BtCLienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtCLienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtCLienteActionPerformed

    private void BtVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtVentasActionPerformed
 Ventas venta= new Ventas ();
 venta.setVisible(true);
 this.dispose();
    }//GEN-LAST:event_BtVentasActionPerformed

    private void BtProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtProductosActionPerformed
    Productos producto= new Productos ();
 producto.setVisible(true);
 this.dispose();
    }//GEN-LAST:event_BtProductosActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Listadoclientes listadocli = new Listadoclientes();
        listadocli.setVisible(true);
        //listadocli.limpiarTablaclientes();
        listadocli.ListaClientes();
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtCLiente;
    private javax.swing.JButton BtProductos;
    private javax.swing.JButton BtProveedor;
    private javax.swing.JButton BtVentas;
    private javax.swing.JButton Btexit;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
